
obstacle_range: 4.0
raytrace_range: 6.0

resolution: 0.05

# footprint: [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]
robot_radius: 0.1
footprint_padding: 0.01

robot_base_frame: base_footprint
update_frequency: 4
publish_frequency: 4
transform_tolerance: 0.5
